// tix-admin/src/App.svelte
<script lang="ts">
  import { parseHash, type Route } from './lib/data/router'
  import DashboardView from './routes/DashboardView.svelte'
  import TicketView from './routes/TicketView.svelte'
  import Button from './lib/components/ui/Button.svelte'
  import { useTickets } from './lib/data/tickets.svelte'
  import { useFilters } from './lib/data/filters.svelte'
  import StatusIcon from './lib/components/icons/StatusIcon.svelte'

  let route = $state<Route>(parseHash(location.hash))
  let dark = $state(false)

  const store = useTickets()
  const filters = useFilters()

  // Derive tag counts from tickets
  const tagCounts = $derived.by(() => {
    const counts: Record<string, number> = {}
    for (const t of store.tickets) {
      for (const tag of t.tags) {
        counts[tag] = (counts[tag] || 0) + 1
      }
    }
    return Object.entries(counts).sort((a, b) => b[1] - a[1])
  })

  const statusCounts = $derived.by(() => {
    const counts: Record<string, number> = { open: 0, 'in-progress': 0, done: 0, closed: 0 }
    for (const t of store.tickets) {
      if (t.status in counts) counts[t.status]++
    }
    return counts
  })

  const statusLabels: Record<string, string> = {
    'open': 'Open',
    'in-progress': 'In Progress',
    'done': 'Done',
    'closed': 'Closed',
  }

  $effect(() => {
    const onHash = () => { route = parseHash(location.hash) }
    window.addEventListener('hashchange', onHash)
    return () => window.removeEventListener('hashchange', onHash)
  })

  function toggleTheme() {
    dark = !dark
    document.documentElement.classList.toggle('dark', dark)
  }

  function toggleStatusFilter(status: string) {
    filters.tagFilter = ''
    filters.statusFilter = filters.statusFilter === status ? '' : status
    if (route.view !== 'dashboard') location.hash = '#/'
  }

  function toggleTagFilter(tag: string) {
    filters.statusFilter = ''
    filters.tagFilter = filters.tagFilter === tag ? '' : tag
    if (route.view !== 'dashboard') location.hash = '#/'
  }
</script>

<div class="flex h-svh bg-background text-foreground overflow-hidden">
  <!-- Sidebar -->
  <aside class="w-60 shrink-0 flex flex-col border-r bg-background">
    <!-- Sidebar header -->
    <div class="h-10 flex items-center px-4 border-b">
      <a href="#/" class="text-sm font-semibold font-mono tracking-tight" onclick={() => filters.clearAll()}>tix</a>
    </div>

    <!-- Nav sections -->
    <nav class="flex-1 overflow-y-auto py-2">
      <!-- All Issues -->
      <div class="px-2 mb-1">
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm cursor-pointer transition-colors {!filters.statusFilter && !filters.tagFilter ? 'bg-accent text-accent-foreground' : 'hover:bg-accent/50 text-foreground'}"
          onclick={() => { filters.clearAll(); location.hash = '#/' }}
        >
          <svg class="h-4 w-4 text-muted-foreground" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22,12 16,12 14,15 10,15 8,12 2,12"/><path d="M5.45,5.11,2,12v6a2,2,0,0,0,2,2H20a2,2,0,0,0,2-2V12l-3.45-6.89A2,2,0,0,0,16.76,4H7.24a2,2,0,0,0-1.79,1.11Z"/></svg>
          <span>All Issues</span>
          <span class="ml-auto text-xs text-muted-foreground">{store.tickets.length}</span>
        </div>
      </div>

      <!-- Status counts -->
      <div class="px-3 mt-4 mb-1">
        <span class="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Status</span>
      </div>
      <div class="px-2">
        {#each Object.entries(statusCounts) as [status, count]}
          <!-- svelte-ignore a11y_click_events_have_key_events -->
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <div
            class="flex items-center gap-2 rounded-md px-2 py-1 text-sm cursor-pointer transition-colors {filters.statusFilter === status ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground'}"
            onclick={() => toggleStatusFilter(status)}
          >
            <StatusIcon {status} size={12} />
            <span>{statusLabels[status]}</span>
            <span class="ml-auto text-xs">{count}</span>
          </div>
        {/each}
      </div>

      <!-- Tags -->
      {#if tagCounts.length > 0}
        <div class="px-3 mt-4 mb-1">
          <span class="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Tags</span>
        </div>
        <div class="px-2">
          {#each tagCounts.slice(0, 12) as [tag, count]}
            <!-- svelte-ignore a11y_click_events_have_key_events -->
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div
              class="flex items-center gap-2 rounded-md px-2 py-1 text-sm cursor-pointer transition-colors {filters.tagFilter === tag ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground'}"
              onclick={() => toggleTagFilter(tag)}
            >
              <svg class="h-3 w-3 shrink-0" viewBox="0 0 16 16" fill="currentColor"><circle cx="8" cy="8" r="4"/></svg>
              <span class="truncate">{tag}</span>
              <span class="ml-auto text-xs">{count}</span>
            </div>
          {/each}
        </div>
      {/if}
    </nav>

    <!-- Sidebar footer -->
    <div class="border-t p-2 flex items-center justify-between">
      <Button variant="ghost" size="icon" class="h-8 w-8" onclick={toggleTheme}>
        {#if dark}
          <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>
        {:else}
          <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>
        {/if}
      </Button>
    </div>
  </aside>

  <!-- Main content area -->
  <div class="flex-1 h-svh overflow-hidden lg:p-2">
    <div class="lg:border lg:rounded-md overflow-hidden flex flex-col h-full bg-background">
      {#if route.view === 'ticket' && route.ticketId}
        <TicketView ticketId={route.ticketId} />
      {:else}
        <DashboardView />
      {/if}
    </div>
  </div>
</div>

// tix-ui-react/src/App.tsx
import { useState, useMemo, useEffect } from 'react'
import { createRouter, createRoute, createRootRoute, RouterProvider, Outlet, useParams, useRouterState } from '@tanstack/react-router'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { useTickets, useUpdateTicket, useConfig } from '@/lib/hooks/use-tickets'
import { AppProvider, useFilters, useViewSettings, useSidebar, useTheme } from '@/lib/AppContext'
import { DashboardView } from '@/routes/DashboardView'
import { TicketView } from '@/routes/TicketView'
import { CommandPalette, type PaletteCallbacks } from '@/components/CommandPalette'
import { StatusIcon } from '@/components/icons/StatusIcon'
import { Button } from '@/components/ui'
import { STATUS_LABELS, type TicketStatus } from '@/lib/types'
import { Sun, Moon, Inbox } from 'lucide-react'

// Query client
const queryClient = new QueryClient({
  defaultOptions: {
    queries: { refetchOnWindowFocus: false },
  },
})

// HMR: refetch tickets on file changes
if (import.meta.hot) {
  import.meta.hot.on('tickets-update', () => {
    queryClient.invalidateQueries({ queryKey: ['tickets'] })
  })
}

function AppLayout() {
  const { data: tickets = [] } = useTickets()
  const updateMutation = useUpdateTicket()
  const { data: config } = useConfig()
  const filters = useFilters()
  const viewSettings = useViewSettings()
  const sidebar = useSidebar()
  const theme = useTheme()
  const [showCreate, setShowCreate] = useState(false)

  const routerState = useRouterState()
  const isTicketView = routerState.location.pathname.startsWith('/ticket/')
  const ticketId = isTicketView ? routerState.location.pathname.split('/ticket/')[1] : undefined
  const currentTicket = ticketId ? tickets.find(t => t.id === ticketId) : undefined

  const ticketsDir = config?.ticketsDir || ''
  const currentFilePath = ticketsDir && currentTicket?.filename ? `${ticketsDir}/${currentTicket.filename}` : ''

  // Document title
  useEffect(() => {
    if (isTicketView && currentTicket) {
      document.title = `tix | ${currentTicket.id} ${currentTicket.title}`
    } else if (filters.statusFilter) {
      document.title = `tix | ${STATUS_LABELS[filters.statusFilter as TicketStatus] ?? filters.statusFilter}`
    } else if (filters.tagFilter) {
      document.title = `tix | #${filters.tagFilter}`
    } else {
      document.title = 'tix | All Issues'
    }
  }, [isTicketView, currentTicket, filters.statusFilter, filters.tagFilter])

  // Tag counts
  const tagCounts = useMemo(() => {
    const counts: Record<string, number> = {}
    for (const t of tickets) {
      for (const tag of t.tags) {
        counts[tag] = (counts[tag] || 0) + 1
      }
    }
    return Object.entries(counts).sort((a, b) => b[1] - a[1])
  }, [tickets])

  // Status counts
  const statusCounts = useMemo(() => {
    const counts: Record<string, number> = { open: 0, 'in-progress': 0, 'on-hold': 0, done: 0, closed: 0 }
    for (const t of tickets) {
      if (t.status in counts) counts[t.status]!++
    }
    return counts
  }, [tickets])

  function toggleStatusFilter(status: string) {
    filters.setTagFilter('')
    filters.setStatusFilter(filters.statusFilter === status ? '' : status)
  }

  function toggleTagFilter(tag: string) {
    filters.setStatusFilter('')
    filters.setTagFilter(filters.tagFilter === tag ? '' : tag)
  }

  const paletteCallbacks: PaletteCallbacks = {
    toggleTheme: theme.toggle,
    toggleSidebar: sidebar.toggle,
    openCreate: () => setShowCreate(true),
    setViewMode: (m) => viewSettings.update({ viewMode: m }),
    setGroupBy: (g) => viewSettings.update({ groupBy: g }),
    setSortBy: (s) => viewSettings.update({ sortBy: s }),
    toggleSortDir: viewSettings.toggleSortDir,
    ...(currentTicket ? {
      updateTicket: (updates) => updateMutation.mutate({ ticketId: currentTicket.id, updates }),
      copyFilePath: currentFilePath ? () => navigator.clipboard.writeText(currentFilePath) : undefined,
      openInVSCode: currentFilePath ? () => window.open(`vscode://file/${currentFilePath}`) : undefined,
      revealInFinder: ticketsDir ? () => window.open(`vscode://file/${ticketsDir}`) : undefined,
    } : {}),
  }

  return (
    <div className="flex h-svh bg-background text-foreground overflow-hidden">
      {/* Sidebar */}
      <aside className={`${sidebar.open ? 'w-60' : 'w-0'} shrink-0 flex flex-col bg-background transition-[width] duration-200 overflow-hidden lg:py-2`}>
        <div className="h-10 flex items-center px-4 min-w-60">
          <a href="/" className="text-sm font-semibold font-mono tracking-tight" onClick={(e) => { e.preventDefault(); filters.clearAll(); window.location.hash = '' }}>tix</a>
        </div>
        <nav className="flex-1 overflow-y-auto py-2">
          <div className="px-2 mb-1">
            <div
              className={`flex items-center gap-2 rounded-md px-2 py-1.5 text-sm cursor-pointer transition-colors ${!filters.statusFilter && !filters.tagFilter ? 'bg-accent text-accent-foreground' : 'hover:bg-accent/50 text-foreground'}`}
              onClick={() => { filters.clearAll() }}
            >
              <Inbox className="h-4 w-4 text-muted-foreground" />
              <span>All Issues</span>
              <span className="ml-auto text-xs text-muted-foreground">{tickets.length}</span>
            </div>
          </div>

          <div className="px-3 mt-4 mb-1">
            <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Status</span>
          </div>
          <div className="px-2">
            {Object.entries(statusCounts).map(([status, count]) => (
              <div
                key={status}
                className={`flex items-center gap-2 rounded-md px-2 py-1 text-sm cursor-pointer transition-colors ${filters.statusFilter === status ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground'}`}
                onClick={() => toggleStatusFilter(status)}
              >
                <StatusIcon status={status} size={12} />
                <span>{STATUS_LABELS[status as TicketStatus]}</span>
                <span className="ml-auto text-xs">{count}</span>
              </div>
            ))}
          </div>

          {tagCounts.length > 0 && (
            <>
              <div className="px-3 mt-4 mb-1">
                <span className="text-[11px] font-medium text-muted-foreground uppercase tracking-wider">Tags</span>
              </div>
              <div className="px-2">
                {tagCounts.slice(0, 12).map(([tag, count]) => (
                  <div
                    key={tag}
                    className={`flex items-center gap-2 rounded-md px-2 py-1 text-sm cursor-pointer transition-colors ${filters.tagFilter === tag ? 'bg-accent text-accent-foreground' : 'text-muted-foreground hover:bg-accent/50 hover:text-foreground'}`}
                    onClick={() => toggleTagFilter(tag)}
                  >
                    <svg className="h-3 w-3 shrink-0" viewBox="0 0 16 16" fill="currentColor"><circle cx="8" cy="8" r="4"/></svg>
                    <span className="truncate">{tag}</span>
                    <span className="ml-auto text-xs">{count}</span>
                  </div>
                ))}
              </div>
            </>
          )}
        </nav>

        <div className="border-t p-2 flex items-center justify-between">
          <Button variant="ghost" size="icon" className="h-8 w-8" onClick={theme.toggle}>
            {theme.dark ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
          </Button>
        </div>
      </aside>

      {/* Main content */}
      <div className="flex-1 h-svh overflow-hidden lg:p-2">
        <div className="lg:border lg:rounded-md overflow-hidden flex flex-col h-full bg-background">
          <Outlet />
        </div>
      </div>

      <CommandPalette tickets={tickets} callbacks={paletteCallbacks} isTicketView={isTicketView} />
    </div>
  )
}

// Routes
const rootRoute = createRootRoute({
  component: AppLayout,
})

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
  component: function Index() {
    return <DashboardViewWrapper />
  },
})

const ticketRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/ticket/$ticketId',
  component: function TicketPage() {
    const { ticketId } = useParams({ from: '/ticket/$ticketId' })
    return <TicketView ticketId={ticketId} />
  },
})

function DashboardViewWrapper() {
  const [showCreate, setShowCreate] = useState(false)
  return <DashboardView showCreate={showCreate} setShowCreate={setShowCreate} />
}

const routeTree = rootRoute.addChildren([indexRoute, ticketRoute])

const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <AppProvider>
        <RouterProvider router={router} />
      </AppProvider>
    </QueryClientProvider>
  )
}
