// tix-ui-start/src/components/KanbanBoard.tsx
import type { Ticket } from '#/lib/types'
import { STATUSES, STATUS_LABELS, STATUS_COLORS } from '#/lib/types'
import { TicketCard } from './TicketCard'
import { StatusIcon } from './icons/StatusIcon'

interface KanbanBoardProps {
  byStatus: Record<string, Ticket[]>
}

export function KanbanBoard({ byStatus }: KanbanBoardProps) {
  return (
    <div className="flex h-full gap-3 px-3 py-3 overflow-x-auto">
      {STATUSES.map(col => (
        <div key={col} className="shrink-0 w-72 flex flex-col rounded-md overflow-hidden">
          <div
            className="h-10 flex items-center justify-between px-3 rounded-t-md"
            style={{ backgroundColor: `${STATUS_COLORS[col]}10` }}
          >
            <div className="flex items-center gap-2">
              <StatusIcon status={col} />
              <span className="text-sm font-medium">{STATUS_LABELS[col]}</span>
              <span className="text-sm text-muted-foreground">{byStatus[col]?.length || 0}</span>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto p-2 space-y-2 bg-muted/30 rounded-b-md">
            {(byStatus[col] || []).map(ticket => (
              <TicketCard key={ticket.id} ticket={ticket} />
            ))}
            {!byStatus[col]?.length && (
              <div className="text-center text-xs text-muted-foreground py-8">No tickets</div>
            )}
          </div>
        </div>
      ))}
    </div>
  )
}

// tix-admin/src/lib/components/KanbanBoard.svelte
<script lang="ts">
  import type { Ticket } from '../types'
  import TicketCard from './TicketCard.svelte'
  import { Badge } from './ui'

  let { byStatus }: { byStatus: Record<string, Ticket[]> } = $props()

  const columns = ['open', 'in-progress', 'done', 'closed'] as const

  const columnLabels: Record<string, string> = {
    'open': 'Open',
    'in-progress': 'In Progress',
    'done': 'Done',
    'closed': 'Closed',
  }
</script>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
  {#each columns as col}
    <div class="flex flex-col gap-2">
      <div class="flex items-center gap-2 border-b pb-2">
        <h2 class="font-semibold text-sm">{columnLabels[col]}</h2>
        <Badge variant="secondary" class="text-[10px] px-1.5 py-0">{byStatus[col]?.length || 0}</Badge>
      </div>
      <div class="flex flex-col gap-2 min-h-24">
        {#each byStatus[col] || [] as ticket (ticket.id)}
          <TicketCard {ticket} />
        {/each}
        {#if !byStatus[col]?.length}
          <div class="text-center text-sm text-muted-foreground py-8">No tickets</div>
        {/if}
      </div>
    </div>
  {/each}
</div>
