// tix-ui-react/src/components/TicketDetail.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import type { Ticket } from '@/lib/types'
import { STATUSES, TYPES, PRIORITIES } from '@/lib/types'
import { Button, Input, Select } from './ui'
import { StatusIcon } from './icons/StatusIcon'
import { PriorityIcon } from './icons/PriorityIcon'
import { MilkdownEditor } from './MilkdownEditor'
import { useConfig } from '@/lib/hooks/use-tickets'
import { useSidebar } from '@/lib/hooks/use-sidebar'
import { useNavigate } from '@tanstack/react-router'
import { PanelLeft, ChevronLeft, Copy, ExternalLink, Folder } from 'lucide-react'

interface TicketDetailProps {
  ticket: Ticket
  onUpdate: (updates: Record<string, any>) => Promise<void> | void
}

function stripLeadingTitle(body: string): string {
  return body.replace(/^\s*#\s+[^\n]*\n*/, '')
}

export function TicketDetail({ ticket, onUpdate }: TicketDetailProps) {
  const navigate = useNavigate()
  const { open: sidebarOpen, toggle: toggleSidebar } = useSidebar()
  const { data: config } = useConfig()
  const ticketsDir = config?.ticketsDir || ''
  const filePath = ticketsDir && ticket.filename ? `${ticketsDir}/${ticket.filename}` : ''

  const [saveState, setSaveState] = useState<'idle' | 'saving' | 'saved' | 'error'>('idle')
  const saveTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)
  const savedTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const displayBody = stripLeadingTitle(ticket.body || '')

  useEffect(() => {
    return () => {
      if (saveTimerRef.current) clearTimeout(saveTimerRef.current)
      if (savedTimerRef.current) clearTimeout(savedTimerRef.current)
    }
  }, [])

  const save = useCallback((updates: Record<string, any>) => {
    if (saveTimerRef.current) clearTimeout(saveTimerRef.current)
    setSaveState('saving')
    if (savedTimerRef.current) clearTimeout(savedTimerRef.current)
    saveTimerRef.current = setTimeout(async () => {
      try {
        await onUpdate(updates)
        setSaveState('saved')
        savedTimerRef.current = setTimeout(() => setSaveState('idle'), 2000)
      } catch {
        setSaveState('error')
      }
    }, 500)
  }, [onUpdate])

  function handleFieldChange(field: string, value: any) {
    save({ [field]: value })
  }

  function handleTagsChange(e: React.ChangeEvent<HTMLInputElement>) {
    const tags = e.target.value.split(',').map(t => t.trim()).filter(Boolean)
    save({ tags })
  }

  function copyPath() {
    if (filePath) navigator.clipboard.writeText(filePath)
  }

  return (
    <>
      {/* Detail header */}
      <div className="w-full flex items-center border-b py-1.5 px-6 h-10">
        <button
          className="h-7 w-7 inline-flex items-center justify-center rounded-md hover:bg-accent transition-colors text-muted-foreground"
          onClick={toggleSidebar}
          title="Toggle sidebar"
        >
          <PanelLeft className="h-4 w-4" />
        </button>
        <Button variant="ghost" size="sm" className="h-7 gap-1 text-xs" onClick={() => navigate({ to: '/' })}>
          <ChevronLeft className="h-4 w-4" />
          Back
        </Button>
        <div className="flex items-center gap-2 ml-3">
          <span className="font-mono text-xs text-muted-foreground">{ticket.id}</span>
          {saveState === 'saving' && <span className="text-xs text-muted-foreground">Saving...</span>}
          {saveState === 'saved' && <span className="text-xs text-muted-foreground">Saved</span>}
          {saveState === 'error' && <span className="text-xs text-destructive">Save failed</span>}
        </div>
        {filePath && (
          <div className="flex items-center gap-1 ml-auto">
            <span className="text-xs text-muted-foreground font-mono truncate max-w-80" title={filePath}>{ticket.filename}</span>
            <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0" onClick={copyPath} title="Copy file path">
              <Copy className="h-3.5 w-3.5" />
            </Button>
            <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0" onClick={() => window.open(`vscode://file/${filePath}`)} title="Open in VS Code">
              <ExternalLink className="h-3.5 w-3.5" />
            </Button>
            <Button variant="ghost" size="icon" className="h-6 w-6 shrink-0" onClick={() => window.open(`vscode://file/${ticketsDir}`)} title="Reveal in Finder">
              <Folder className="h-3.5 w-3.5" />
            </Button>
          </div>
        )}
      </div>

      {/* Detail content */}
      <div className="flex-1 overflow-auto">
        <div className="max-w-3xl mx-auto py-6 px-6">
          <input
            type="text"
            className="w-full bg-transparent text-2xl font-bold border-none outline-none placeholder:text-muted-foreground mb-4"
            defaultValue={ticket.title}
            onChange={(e) => handleFieldChange('title', e.target.value)}
            placeholder="Ticket title"
          />

          <div className="flex flex-wrap items-center gap-2 mb-4">
            <div className="flex items-center gap-1.5 border rounded-md px-2 h-8">
              <StatusIcon status={ticket.status} />
              <Select
                className="w-auto h-7 text-sm border-none shadow-none bg-transparent px-0"
                defaultValue={ticket.status}
                onChange={(e) => handleFieldChange('status', e.target.value)}
              >
                {STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
              </Select>
            </div>

            <div className="flex items-center gap-1.5 border rounded-md px-2 h-8">
              <PriorityIcon priority={ticket.priority} size={14} />
              <Select
                className="w-auto h-7 text-sm border-none shadow-none bg-transparent px-0"
                defaultValue={ticket.priority}
                onChange={(e) => handleFieldChange('priority', Number(e.target.value))}
              >
                {PRIORITIES.map(p => <option key={p} value={p}>P{p}</option>)}
              </Select>
            </div>

            <Select
              className="w-auto h-8 text-sm"
              defaultValue={ticket.type}
              onChange={(e) => handleFieldChange('type', e.target.value)}
            >
              {TYPES.map(t => <option key={t} value={t}>{t}</option>)}
            </Select>

            <Input
              type="text"
              className="w-40 h-8 text-sm"
              defaultValue={ticket.assignee}
              onChange={(e) => handleFieldChange('assignee', e.target.value)}
              placeholder="Assignee"
            />
          </div>

          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mb-4 text-xs text-muted-foreground">
            {ticket.created && (
              <span>Created {new Date(ticket.created).toLocaleDateString()}</span>
            )}
            <span>Tags:</span>
            <Input
              type="text"
              className="flex-1 h-8 text-sm"
              defaultValue={ticket.tags.join(', ')}
              onChange={handleTagsChange}
              placeholder="tag1, tag2, ..."
            />
          </div>

          {ticket.deps.length > 0 && (
            <div className="text-sm mb-2">
              <span className="text-muted-foreground">Dependencies:</span>
              {ticket.deps.map(dep => (
                <a key={dep} href={`#/ticket/${dep}`} className="text-primary underline underline-offset-4 font-mono ml-1" onClick={(e) => { e.preventDefault(); navigate({ to: '/ticket/$ticketId', params: { ticketId: dep } }) }}>{dep}</a>
              ))}
            </div>
          )}

          {ticket.links.length > 0 && (
            <div className="text-sm mb-2">
              <span className="text-muted-foreground">Links:</span>
              {ticket.links.map(link => (
                <a key={link} href={`#/ticket/${link}`} className="text-primary underline underline-offset-4 font-mono ml-1" onClick={(e) => { e.preventDefault(); navigate({ to: '/ticket/$ticketId', params: { ticketId: link } }) }}>{link}</a>
              ))}
            </div>
          )}

          <hr className="border-border my-4" />

          <div className="min-h-50">
            <MilkdownEditor defaultValue={displayBody} onChange={(md) => save({ body: md })} />
          </div>
        </div>
      </div>
    </>
  )
}

// tix-admin/src/lib/components/TicketDetail.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { Ticket } from '../types'
  import { Button, Input, Select } from './ui'
  import StatusIcon from './icons/StatusIcon.svelte'
  import PriorityIcon from './icons/PriorityIcon.svelte'

  let { ticket, onUpdate }: {
    ticket: Ticket,
    onUpdate?: (updates: Record<string, any>) => void
  } = $props()

  const statuses = ['open', 'in-progress', 'done', 'closed']
  const types = ['task', 'bug', 'feature', 'epic']
  const priorities = [0, 1, 2, 3, 4]

  // Debounced save
  let saveTimer: ReturnType<typeof setTimeout> | null = null
  function save(updates: Record<string, any>) {
    if (saveTimer) clearTimeout(saveTimer)
    saveTimer = setTimeout(() => {
      onUpdate?.(updates)
    }, 500)
  }

  // Strip leading # Title from body for display (title shown in input instead)
  function stripLeadingTitle(body: string): string {
    return body.replace(/^\s*#\s+[^\n]*\n*/, '')
  }

  // Milkdown Crepe
  let editorContainer: HTMLDivElement
  let crepe: any = null
  let displayBody = stripLeadingTitle(ticket.body || '')
  let lastBody = displayBody

  onMount(async () => {
    const { Crepe } = await import('@milkdown/crepe')
    await import('@milkdown/crepe/theme/common/style.css')
    await import('@milkdown/crepe/theme/frame.css')

    crepe = new Crepe({
      root: editorContainer,
      defaultValue: displayBody,
    })

    crepe.on((listener: any) => {
      listener.markdownUpdated((_ctx: any, markdown: string) => {
        if (markdown !== lastBody) {
          lastBody = markdown
          save({ body: markdown })
        }
      })
    })

    await crepe.create()
  })

  onDestroy(() => {
    if (saveTimer) clearTimeout(saveTimer)
    crepe?.destroy()
  })

  function handleFieldChange(field: string, value: any) {
    save({ [field]: value })
  }

  function handleTagsChange(e: Event) {
    const input = e.target as HTMLInputElement
    const tags = input.value.split(',').map(t => t.trim()).filter(Boolean)
    save({ tags })
  }
</script>

<!-- Detail header -->
<div class="w-full flex items-center border-b py-1.5 px-6 h-10">
  <Button variant="ghost" size="sm" class="h-7 gap-1 text-xs" onclick={() => location.hash = '#/'}>
    <svg class="h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg>
    Back
  </Button>
  <div class="flex items-center gap-2 ml-3">
    <span class="font-mono text-xs text-muted-foreground">{ticket.id}</span>
    {#if ticket.created}
      <span class="text-xs text-muted-foreground">
        {new Date(ticket.created).toLocaleDateString()}
      </span>
    {/if}
  </div>
</div>

<!-- Detail content -->
<div class="flex-1 overflow-auto">
  <div class="max-w-3xl mx-auto py-6 px-6">
    <!-- Title -->
    <input
      type="text"
      class="w-full bg-transparent text-2xl font-bold border-none outline-none placeholder:text-muted-foreground mb-4"
      value={ticket.title}
      onchange={(e) => handleFieldChange('title', (e.target as HTMLInputElement).value)}
      placeholder="Ticket title"
    />

    <!-- Metadata row -->
    <div class="flex flex-wrap items-center gap-2 mb-4">
      <div class="flex items-center gap-1.5 border rounded-md px-2 h-8">
        <StatusIcon status={ticket.status} />
        <Select
          class="w-auto h-7 text-sm border-none shadow-none bg-transparent px-0"
          value={ticket.status}
          onchange={(e) => handleFieldChange('status', (e.target as HTMLSelectElement).value)}
        >
          {#each statuses as s}
            <option value={s}>{s}</option>
          {/each}
        </Select>
      </div>

      <div class="flex items-center gap-1.5 border rounded-md px-2 h-8">
        <PriorityIcon priority={ticket.priority} size={14} />
        <Select
          class="w-auto h-7 text-sm border-none shadow-none bg-transparent px-0"
          value={ticket.priority}
          onchange={(e) => handleFieldChange('priority', Number((e.target as HTMLSelectElement).value))}
        >
          {#each priorities as p}
            <option value={p}>P{p}</option>
          {/each}
        </Select>
      </div>

      <Select
        class="w-auto h-8 text-sm"
        value={ticket.type}
        onchange={(e) => handleFieldChange('type', (e.target as HTMLSelectElement).value)}
      >
        {#each types as t}
          <option value={t}>{t}</option>
        {/each}
      </Select>

      <Input
        type="text"
        class="w-40 h-8 text-sm"
        value={ticket.assignee}
        onchange={(e) => handleFieldChange('assignee', (e.target as HTMLInputElement).value)}
        placeholder="Assignee"
      />
    </div>

    <!-- Tags -->
    <div class="flex items-center gap-2 mb-4">
      <span class="text-xs text-muted-foreground">Tags:</span>
      <Input
        type="text"
        class="flex-1 h-8 text-sm"
        value={ticket.tags.join(', ')}
        onchange={handleTagsChange}
        placeholder="tag1, tag2, ..."
      />
    </div>

    <!-- Dependencies / Links -->
    {#if ticket.deps.length > 0}
      <div class="text-sm mb-2">
        <span class="text-muted-foreground">Dependencies:</span>
        {#each ticket.deps as dep}
          <a href="#/ticket/{dep}" class="text-primary underline underline-offset-4 font-mono ml-1">{dep}</a>
        {/each}
      </div>
    {/if}

    {#if ticket.links.length > 0}
      <div class="text-sm mb-2">
        <span class="text-muted-foreground">Links:</span>
        {#each ticket.links as link}
          <a href="#/ticket/{link}" class="text-primary underline underline-offset-4 font-mono ml-1">{link}</a>
        {/each}
      </div>
    {/if}

    <hr class="border-border my-4" />

    <!-- Milkdown editor -->
    <div bind:this={editorContainer} class="milkdown-editor prose prose-sm max-w-none min-h-50 dark:prose-invert"></div>
  </div>
</div>

<style>
  .milkdown-editor :global(.milkdown) {
    outline: none;
    background: transparent;
    padding: 8px 0;
  }
  .milkdown-editor :global(.milkdown .editor) {
    padding: 0;
  }
</style>
