// tix-admin/src/lib/components/ui/Card.svelte
<script lang="ts">
  import { cn } from '../../utils'
  import type { Snippet } from 'svelte'

  let {
    class: className = '',
    children,
  }: {
    class?: string
    children?: Snippet
  } = $props()
</script>

<div class={cn('rounded-xl border bg-card text-card-foreground shadow', className)}>
  {#if children}{@render children()}{/if}
</div>

// tix-ui-react/src/components/ui/Card.tsx
import { forwardRef, type HTMLAttributes } from 'react'
import { cn } from '@/lib/utils'

export const Card = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn('rounded-lg border bg-card text-card-foreground shadow-sm', className)}
      {...props}
    />
  )
)
Card.displayName = 'Card'
