// tix-ui/src/lib/components/TicketTable.svelte
<script lang="ts">
  import type { Ticket } from '../types'
  import type { GroupBy } from '../data/view-settings.svelte'
  import { Badge } from './ui'
  import StatusIcon from './icons/StatusIcon.svelte'
  import PriorityIcon from './icons/PriorityIcon.svelte'
  import StatusSelector from './StatusSelector.svelte'
  import PrioritySelector from './PrioritySelector.svelte'
  import TypeSelector from './TypeSelector.svelte'
  import TypeIcon from './icons/TypeIcon.svelte'

  let { tickets, grouped, groupBy, onUpdate }: {
    tickets: Ticket[]
    grouped: Record<string, Ticket[]>
    groupBy: GroupBy
    onUpdate?: (ticketId: string, updates: Record<string, any>) => void
  } = $props()

  const statusColors: Record<string, string> = {
    'open': '#f97316',
    'in-progress': '#facc15',
    'done': '#8b5cf6',
    'closed': '#94a3b8',
  }

  const statusLabels: Record<string, string> = {
    'open': 'Open',
    'in-progress': 'In Progress',
    'done': 'Done',
    'closed': 'Closed',
  }

  const priorityLabels: Record<string, string> = {
    '0': 'P0 Urgent', '1': 'P1 High', '2': 'P2 Medium', '3': 'P3 Low', '4': 'P4 None',
  }

  // Order groups sensibly depending on groupBy
  const orderedGroups = $derived.by(() => {
    const keys = Object.keys(grouped)
    if (groupBy === 'status') {
      const order = ['open', 'in-progress', 'on-hold', 'done', 'closed']
      return order.filter(k => keys.includes(k))
    }
    if (groupBy === 'priority') {
      return ['0', '1', '2', '3', '4'].filter(k => keys.includes(k))
    }
    return keys.sort()
  })

  function groupLabel(key: string): string {
    if (groupBy === 'status') return statusLabels[key] || key
    if (groupBy === 'priority') return priorityLabels[key] || `P${key}`
    if (groupBy === 'type') return key.charAt(0).toUpperCase() + key.slice(1)
    return key
  }

  function groupColor(key: string): string {
    if (groupBy === 'status') return statusColors[key] || '#94a3b8'
    return '#94a3b8'
  }
</script>

<div class="w-full">
  {#each orderedGroups as groupKey}
    {#if groupBy !== 'none'}
      <!-- Group header -->
      <div
        class="sticky top-0 z-10 w-full h-10 flex items-center justify-between px-6"
        style="background-color: {groupColor(groupKey)}08"
      >
        <div class="flex items-center gap-2">
          {#if groupBy === 'status'}
            <StatusIcon status={groupKey} />
          {:else if groupBy === 'priority'}
            <PriorityIcon priority={Number(groupKey)} size={14} />
          {:else if groupBy === 'type'}
            <TypeIcon type={groupKey} size={14} />
          {/if}
          <span class="text-sm font-medium">{groupLabel(groupKey)}</span>
          <span class="text-sm text-muted-foreground">{grouped[groupKey].length}</span>
        </div>
      </div>
    {/if}

    <!-- Issue rows -->
    {#each grouped[groupKey] as ticket (ticket.id)}
      <div
        class="w-full flex items-center justify-start h-11 px-6 hover:bg-accent/50 cursor-pointer transition-colors"
        onclick={() => location.hash = `#/ticket/${ticket.id}`}
        role="button"
        tabindex="0"
        onkeydown={(e) => { if (e.key === 'Enter') location.hash = `#/ticket/${ticket.id}` }}
      >
        <!-- Priority -->
        <!-- svelte-ignore a11y_no_static_element_interactions a11y_click_events_have_key_events -->
        <span class="w-8 shrink-0 flex items-center justify-center" onclick={(e) => e.stopPropagation()}>
          <PrioritySelector
            priority={ticket.priority}
            onSelect={(p) => onUpdate?.(ticket.id, { priority: p })}
            compact
          />
        </span>

        <!-- ID -->
        <span class="w-14 shrink-0 text-sm hidden sm:inline-block text-muted-foreground font-medium font-mono truncate">
          {ticket.id}
        </span>

        <!-- Status -->
        <!-- svelte-ignore a11y_no_static_element_interactions a11y_click_events_have_key_events -->
        <span class="w-8 shrink-0 flex items-center justify-center" onclick={(e) => e.stopPropagation()}>
          <StatusSelector
            status={ticket.status}
            onSelect={(s) => onUpdate?.(ticket.id, { status: s })}
            compact
          />
        </span>

        <!-- Title -->
        <span class="min-w-0 flex-1 truncate text-xs sm:text-sm font-medium sm:font-semibold">
          {ticket.title}
        </span>

        <!-- Right: tags, date, assignee -->
        <div class="flex items-center justify-end gap-2 ml-2 shrink-0">
          <div class="items-center justify-end hidden sm:flex gap-1">
            {#each ticket.tags.slice(0, 3) as tag}
              <Badge variant="outline" class="text-[10px] px-1.5 py-0 rounded-full">{tag}</Badge>
            {/each}
          </div>
          <!-- svelte-ignore a11y_no_static_element_interactions a11y_click_events_have_key_events -->
          <span class="hidden sm:flex w-8 shrink-0 items-center justify-center" onclick={(e) => e.stopPropagation()}>
            <TypeSelector
              type={ticket.type}
              onSelect={(t) => onUpdate?.(ticket.id, { type: t })}
              compact
            />
          </span>
          {#if ticket.created}
            <span class="text-xs text-muted-foreground shrink-0 hidden sm:inline-block w-16 text-right">
              {new Date(ticket.created).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
            </span>
          {/if}
          {#if ticket.assignee}
            <span class="w-6 h-6 rounded-full bg-muted flex items-center justify-center text-[10px] font-medium shrink-0" title={ticket.assignee}>
              {ticket.assignee.charAt(0).toUpperCase()}
            </span>
          {:else}
            <span class="w-6 h-6 rounded-full border border-dashed border-muted-foreground/30 shrink-0"></span>
          {/if}
        </div>
      </div>
    {/each}
  {/each}
</div>

// tix-ui/src/components/TicketTable.tsx
import type { Ticket, GroupBy, TicketStatus } from '#/lib/types'
import { STATUS_LABELS, STATUS_COLORS } from '#/lib/types'
import { Badge } from './ui'
import { StatusIcon } from './icons/StatusIcon'
import { PriorityIcon } from './icons/PriorityIcon'
import { TypeIcon } from './icons/TypeIcon'
import { StatusSelector } from './StatusSelector'
import { PrioritySelector } from './PrioritySelector'
import { TypeSelector } from './TypeSelector'
import { useNavigate } from '@tanstack/react-router'
import { useMemo, useState, useEffect } from 'react'
import { ChevronDown, ChevronRight } from 'lucide-react'

interface TicketTableProps {
  grouped: Record<string, Ticket[]>
  groupBy: GroupBy
  onUpdate?: (ticketId: string, updates: Record<string, any>) => void
}

const priorityLabels: Record<string, string> = {
  '0': 'P0 Urgent', '1': 'P1 High', '2': 'P2 Medium', '3': 'P3 Low', '4': 'P4 None',
}

function groupLabel(key: string, groupBy: GroupBy): string {
  if (groupBy === 'status') return STATUS_LABELS[key as TicketStatus] || key
  if (groupBy === 'priority') return priorityLabels[key] || `P${key}`
  if (groupBy === 'type') return key.charAt(0).toUpperCase() + key.slice(1)
  return key
}

function groupColor(key: string, groupBy: GroupBy): string {
  if (groupBy === 'status') return STATUS_COLORS[key as TicketStatus] || '#94a3b8'
  return '#94a3b8'
}

// Persist collapsed group keys per-groupBy in localStorage so the state
// survives reloads and switching between groupings.
const COLLAPSE_STORAGE_KEY = 'tix-ui:collapsed-groups'

function loadCollapsed(): Record<string, string[]> {
  if (typeof window === 'undefined') return {}
  try {
    const raw = localStorage.getItem(COLLAPSE_STORAGE_KEY)
    return raw ? JSON.parse(raw) : {}
  } catch {
    return {}
  }
}

function saveCollapsed(state: Record<string, string[]>) {
  if (typeof window === 'undefined') return
  try { localStorage.setItem(COLLAPSE_STORAGE_KEY, JSON.stringify(state)) } catch { /* ignore */ }
}

export function TicketTable({ grouped, groupBy, onUpdate }: TicketTableProps) {
  const navigate = useNavigate()

  const [collapsed, setCollapsed] = useState<Set<string>>(() => new Set())

  // Load persisted state when groupBy changes.
  useEffect(() => {
    const all = loadCollapsed()
    setCollapsed(new Set(all[groupBy] || []))
  }, [groupBy])

  function toggleGroup(key: string) {
    setCollapsed(prev => {
      const next = new Set(prev)
      if (next.has(key)) next.delete(key)
      else next.add(key)
      const all = loadCollapsed()
      all[groupBy] = Array.from(next)
      saveCollapsed(all)
      return next
    })
  }

  const orderedGroups = useMemo(() => {
    const keys = Object.keys(grouped)
    if (groupBy === 'status') {
      const order = ['open', 'in-progress', 'review', 'on-hold', 'done', 'closed']
      return order.filter(k => keys.includes(k))
    }
    if (groupBy === 'priority') {
      return ['0', '1', '2', '3', '4'].filter(k => keys.includes(k))
    }
    return keys.sort()
  }, [grouped, groupBy])

  return (
    <div className="w-full">
      {orderedGroups.map(groupKey => (
        <div key={groupKey}>
          {groupBy !== 'none' && (
            <div
              className="sticky top-0 z-10 w-full h-10 flex items-center justify-between px-6 bg-background cursor-pointer select-none"
              // Solid background so sticky headers don't let scrolling rows
              // bleed through; color-mix blends the group tint into the
              // theme bg so we still get a subtle color accent.
              style={{ backgroundColor: `color-mix(in srgb, ${groupColor(groupKey, groupBy)} 6%, var(--background))` }}
              onClick={() => toggleGroup(groupKey)}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); toggleGroup(groupKey) } }}
              aria-expanded={!collapsed.has(groupKey)}
            >
              <div className="flex items-center gap-2">
                {collapsed.has(groupKey)
                  ? <ChevronRight className="h-3.5 w-3.5 text-muted-foreground" />
                  : <ChevronDown className="h-3.5 w-3.5 text-muted-foreground" />}
                {groupBy === 'status' && <StatusIcon status={groupKey} />}
                {groupBy === 'priority' && <PriorityIcon priority={Number(groupKey)} size={14} />}
                {groupBy === 'type' && <TypeIcon type={groupKey} size={14} />}
                <span className="text-sm font-medium">{groupLabel(groupKey, groupBy)}</span>
                <span className="text-sm text-muted-foreground">{grouped[groupKey]?.length}</span>
              </div>
            </div>
          )}

          {!collapsed.has(groupKey) && (grouped[groupKey] || []).map(ticket => (
            <div
              key={ticket.id}
              className="w-full flex items-center justify-start h-11 px-6 hover:bg-accent/50 cursor-pointer transition-colors"
              onClick={() => navigate({ to: '/ticket/$ticketId', params: { ticketId: ticket.id } })}
              role="button"
              tabIndex={0}
              onKeyDown={(e) => { if (e.key === 'Enter') navigate({ to: '/ticket/$ticketId', params: { ticketId: ticket.id } }) }}
            >
              <span className="w-8 shrink-0 flex items-center justify-center" onClick={e => e.stopPropagation()}>
                <PrioritySelector
                  priority={ticket.priority}
                  onSelect={(p) => onUpdate?.(ticket.id, { priority: p })}
                  compact
                />
              </span>
              <span className="w-14 shrink-0 text-sm hidden sm:inline-block text-muted-foreground font-medium font-mono truncate">
                {ticket.id}
              </span>
              <span className="w-8 shrink-0 flex items-center justify-center" onClick={e => e.stopPropagation()}>
                <StatusSelector
                  status={ticket.status}
                  onSelect={(s) => onUpdate?.(ticket.id, { status: s })}
                  compact
                />
              </span>
              <span className="min-w-0 flex-1 truncate text-xs sm:text-sm font-medium sm:font-semibold">
                {ticket.title}
              </span>
              <div className="flex items-center justify-end gap-2 ml-2 shrink-0">
                <div className="items-center justify-end hidden sm:flex gap-1">
                  {ticket.tags.slice(0, 3).map(tag => (
                    <Badge key={tag} variant="outline" className="text-[10px] px-1.5 py-0 rounded-full">{tag}</Badge>
                  ))}
                </div>
                <span className="hidden sm:flex w-8 shrink-0 items-center justify-center" onClick={e => e.stopPropagation()}>
                  <TypeSelector
                    type={ticket.type}
                    onSelect={(t) => onUpdate?.(ticket.id, { type: t })}
                    compact
                  />
                </span>
                {ticket.created && (
                  <span className="text-xs text-muted-foreground shrink-0 hidden sm:inline-block w-16 text-right">
                    {new Date(ticket.created).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                  </span>
                )}
                {ticket.assignee ? (
                  <span className="w-6 h-6 rounded-full bg-muted flex items-center justify-center text-[10px] font-medium shrink-0" title={ticket.assignee}>
                    {ticket.assignee.charAt(0).toUpperCase()}
                  </span>
                ) : (
                  <span className="w-6 h-6 rounded-full border border-dashed border-muted-foreground/30 shrink-0" />
                )}
              </div>
            </div>
          ))}
        </div>
      ))}
    </div>
  )
}
