// tix-admin/src/lib/components/ui/Select.svelte
<script lang="ts">
  import { cn } from '../../utils'
  import type { HTMLSelectAttributes } from 'svelte/elements'
  import type { Snippet } from 'svelte'

  let {
    class: className = '',
    value = $bindable(''),
    children,
    ...rest
  }: HTMLSelectAttributes & { class?: string; value?: any; children?: Snippet } = $props()
</script>

<select
  bind:value
  class={cn(
    'flex h-9 w-full items-center justify-between rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50',
    className
  )}
  {...rest}
>
  {#if children}{@render children()}{/if}
</select>

// tix-ui-start/src/components/ui/Select.tsx
import { forwardRef, type SelectHTMLAttributes } from 'react'
import { cn } from '#/lib/utils'

export const Select = forwardRef<HTMLSelectElement, SelectHTMLAttributes<HTMLSelectElement>>(
  ({ className, ...props }, ref) => (
    <select
      ref={ref}
      className={cn(
        'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-sm shadow-sm focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring',
        className,
      )}
      {...props}
    />
  )
)
Select.displayName = 'Select'
