// tix-ui/src/components/TicketCard.tsx
import type { Ticket } from '#/lib/types'
import { Badge, Card } from './ui'
import { StatusIcon } from './icons/StatusIcon'
import { PriorityIcon } from './icons/PriorityIcon'
import { useNavigate } from '@tanstack/react-router'

interface TicketCardProps {
  ticket: Ticket
  onClick?: (id: string) => void
  selected?: boolean
}

export function TicketCard({ ticket, onClick, selected }: TicketCardProps) {
  const navigate = useNavigate()
  const open = () => {
    if (onClick) onClick(ticket.id)
    else navigate({ to: '/ticket/$ticketId', params: { ticketId: ticket.id } })
  }

  return (
    <div className="block cursor-pointer group" onClick={open}>
      <Card className={`p-3 transition-colors ${selected ? 'bg-accent ring-1 ring-ring' : 'hover:bg-accent/50'}`}>
        <div className="flex items-center gap-1.5 mb-1">
          <PriorityIcon priority={ticket.priority} size={14} />
          <span className="font-mono text-xs text-muted-foreground">{ticket.id}</span>
          <StatusIcon status={ticket.status} size={12} />
        </div>
        <h3 className="text-sm font-medium leading-snug mb-1.5">{ticket.title}</h3>
        <div className="flex items-center gap-1 flex-wrap">
          {ticket.tags.map(tag => (
            <Badge key={tag} variant="outline" className="text-[10px] px-1.5 py-0 rounded-full">{tag}</Badge>
          ))}
          {ticket.assignee && (
            <span className="ml-auto w-5 h-5 rounded-full bg-muted flex items-center justify-center text-[9px] font-medium" title={ticket.assignee}>
              {ticket.assignee.charAt(0).toUpperCase()}
            </span>
          )}
        </div>
      </Card>
    </div>
  )
}

// tix-ui/src/lib/components/TicketCard.svelte
<script lang="ts">
  import type { Ticket } from '../types'
  import { Badge, Card } from './ui'
  import StatusIcon from './icons/StatusIcon.svelte'
  import PriorityIcon from './icons/PriorityIcon.svelte'

  let { ticket }: { ticket: Ticket } = $props()
</script>

<a href="#/ticket/{ticket.id}" class="block group">
  <Card class="p-3 transition-colors hover:bg-accent/50">
    <div class="flex items-center gap-1.5 mb-1">
      <PriorityIcon priority={ticket.priority} size={14} />
      <span class="font-mono text-xs text-muted-foreground">{ticket.id}</span>
      <StatusIcon status={ticket.status} size={12} />
    </div>
    <h3 class="text-sm font-medium leading-snug mb-1.5">{ticket.title}</h3>
    <div class="flex items-center gap-1 flex-wrap">
      {#each ticket.tags as tag}
        <Badge variant="outline" class="text-[10px] px-1.5 py-0 rounded-full">{tag}</Badge>
      {/each}
      {#if ticket.assignee}
        <span class="ml-auto w-5 h-5 rounded-full bg-muted flex items-center justify-center text-[9px] font-medium" title={ticket.assignee}>
          {ticket.assignee.charAt(0).toUpperCase()}
        </span>
      {/if}
    </div>
  </Card>
</a>
