// tix-ui-react/src/components/ui/Badge.tsx
import type { HTMLAttributes } from 'react'
import { cn } from '@/lib/utils'

const variants = {
  default: 'bg-primary text-primary-foreground',
  secondary: 'bg-secondary text-secondary-foreground',
  outline: 'border text-foreground',
  destructive: 'bg-destructive text-destructive-foreground',
} as const

interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: keyof typeof variants
}

export function Badge({ className, variant = 'default', ...props }: BadgeProps) {
  return (
    <span
      className={cn(
        'inline-flex items-center rounded-md border border-transparent px-2.5 py-0.5 text-xs font-semibold transition-colors',
        variants[variant],
        className,
      )}
      {...props}
    />
  )
}

// tix-admin/src/lib/components/ui/Badge.svelte
<script lang="ts">
  import { cn } from '../../utils'
  import type { Snippet } from 'svelte'

  type Variant = 'default' | 'secondary' | 'destructive' | 'outline'

  let {
    variant = 'default',
    class: className = '',
    children,
  }: {
    variant?: Variant
    class?: string
    children?: Snippet
  } = $props()

  const variants: Record<Variant, string> = {
    default: 'bg-primary text-primary-foreground hover:bg-primary/80',
    secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
    destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/80',
    outline: 'text-foreground border border-input',
  }
</script>

<span class={cn(
  'inline-flex items-center rounded-md border border-transparent px-2.5 py-0.5 text-xs font-semibold transition-colors',
  variants[variant],
  className
)}>
  {#if children}{@render children()}{/if}
</span>
