// tix-ui-react/src/components/ui/Dialog.tsx
import { useEffect, useRef, type ReactNode } from 'react'
import { cn } from '@/lib/utils'

interface DialogProps {
  open: boolean
  onClose: () => void
  className?: string
  children: ReactNode
}

export function Dialog({ open, onClose, className, children }: DialogProps) {
  const overlayRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!open) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [open, onClose])

  if (!open) return null

  return (
    <div
      ref={overlayRef}
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm"
      onClick={(e) => { if (e.target === overlayRef.current) onClose() }}
    >
      <div className={cn('relative bg-popover text-popover-foreground border rounded-lg shadow-lg w-full sm:max-w-lg p-6', className)}>
        {children}
      </div>
    </div>
  )
}

// tix-ui/src/lib/components/ui/Dialog.svelte
<script lang="ts">
  import { cn } from '../../utils'
  import type { Snippet } from 'svelte'

  let {
    open = false,
    onClose,
    class: className = '',
    children,
  }: {
    open?: boolean
    onClose?: () => void
    class?: string
    children?: Snippet
  } = $props()

  $effect(() => {
    if (!open) return
    const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') onClose?.() }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  })
</script>

{#if open}
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="fixed inset-0 z-50 flex items-center justify-center">
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <div class="fixed inset-0 bg-black/80" onclick={onClose}></div>
    <div class={cn(
      'relative z-50 w-full max-w-lg rounded-lg border bg-background p-6 shadow-lg',
      className
    )}>
      {#if children}{@render children()}{/if}
    </div>
  </div>
{/if}
